import os
from typing import Optional
from jose import JWTError, jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from dotenv import load_dotenv
from database import get_db

load_dotenv()

# We'll use NEXTAUTH_SECRET to decode the token sent by Next.js
SECRET_KEY = os.getenv("NEXTAUTH_SECRET", "lawgpt_super_secret_key")
ALGORITHM = "HS256"

# We use tokenUrl="" since login is handled by NextAuth
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="")

async def get_current_user(token: str = Depends(oauth2_scheme), db = Depends(get_db)):
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        # Decode the token generated by NextAuth
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        
        # NextAuth includes the email directly in the token payload
        email: str = payload.get("email")
        if email is None:
            raise credentials_exception
    except JWTError:
        raise credentials_exception
    
    # Check if user exists in the NextAuth users collection
    user = await db.users.find_one({"email": email})
    if user is None:
        raise credentials_exception
    return user
